version: "3"

services:
  phoenix:
    build: .
    volumes:
      - ./src:/app
    ports:
      - "4000:4000"
    depends_on:
      - db

  db: 
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/PGDATA
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data